### ISSUE TITLE
Same client from the snippets

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#70]
https://user-images.githubusercontent.com/74157486/163563817-dadbd6a8-044f-4f92-9e72-54002514e703.MOV

 it's shutting down as soon as you put your email in
The spin doesn't finish, doesn't begin in fact (both mobile and desktop)

customer: onglessky
[ongles-sky.myshopify.com](https://ongles-sky.myshopify.com/)

**Comment by EcomGraduatesDev** [comment]
I can't check what these settings are since we don't have proper access to the client's store but as a start, we should confirm that it is not checked.

https://ongles-sky.myshopify.com/admin/online_store/preferences

![Screen Shot 2022-04-16 at 9 28 36 AM](https://user-images.githubusercontent.com/90354202/163666121-6df5a7e3-c7e4-40d6-8897-b3988079e8d9.png)
