### ISSUE TITLE
another customer having issues with spin to win  

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#71]
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/74157486/163695435-ea0c0614-629a-4163-935a-5afe2a5e173a.png">

- [ ] not  working on all  pages  
- [ ] not working if recaptha  is enabled  ( should work if it is  or isnt)  

[charmful-impressions.myshopify.com](https://charmful-impressions.myshopify.com/)

**Comment by EcomGraduates** [comment]
theme copy called “ dawn spinning wheel test”

**Comment by EcomGraduatesDev** [comment]
- With ReCaptcha enabled it can not possibly work since Shopify will automatically forward the form to the page where the users have to complete the ReCaptcha verification. Still, I recommend that the client disable the Recaptcha and if they notice spam flood they can enable it, again. The spinning wheel is meant to be offered from time to time for various promotions and not stay published all the time. 

The other approach would be to disable the newsletter form and just have a button that says sth like "Spin to win". For this, we need admin access to the client store, so that we can implement directly the changes.

- The second issue is solved and more info can be found here #72
